export const SET_JOKES = "SET_JOKES";
export const SET_PROFILE_JOKE = "SET_PROFILE_JOKE";
export const ADD_PROFILE_JOKE = "ADD_PROFILE_JOKE";
export const REMOVE_PROFILE_JOKE = "REMOVE_PROFILE_JOKE";
